title: Ray Al Haraz
logo: /assets/img/headshot.jpg   # replace with your image path
description: >
  Aerospace Engineer  
  University at Buffalo Graduate (2025)

show_downloads: false
theme: jekyll-theme-minimal

# Add contact/social links for sidebar
linkedin: https://www.linkedin.com/in/rayalhar
github: https://github.com/rayalhar
email: rayalharaz@gmail.com
resume: /assets/RayAlHaraz_Resume.pdf
