title: Ray Al Haraz
logo: /assets/img/headshot.jpg
theme: jekyll-theme-minimal

description: |
  <strong>Aerospace Engineer — University at Buffalo (2025)</strong><br><br>
  <h3>About Me</h3>
  <p>
  I’m an aerospace engineer with a background in satellite systems and a wide range of tech skills. I’ve had the chance to blend engineering, problem-solving, and people skills in ways that aren’t typical for most engineers.
  </p>
  <p>
  I enjoy tackling challenges where I can learn and grow; whether in aerospace, engineering, or any technology-driven space.
  </p>
  <br>
  <a href="mailto:rayalharaz@gmail.com">rayalharaz@gmail.com</a><br>
  <a href="https://www.linkedin.com/in/rayalhar" target="_blank">LinkedIn</a> ·
  <a href="https://github.com/rayalhar" target="_blank">GitHub</a><br><br>
  <a href="https://drive.google.com/uc?export=download&id=1d4pCs4y9w8Ogq-VaR6GiQuRELpzx6r0-" target="_blank"
     style="display:inline-block;padding:8px 12px;margin-top:6px;border:1px solid #007acc;
            border-radius:6px;background:#007acc;color:#fff;text-decoration:none;font-weight:bold;">
     ⬇ Download My Résumé
  </a>
