title: Ray Al Haraz
logo: /assets/img/headshot.jpg
theme: jekyll-theme-minimal

# This text renders in the LEFT sidebar under your name/photo.
description: |
  <h3>About Me</h3>
  <p>
  I’m an aerospace engineer who’s spent a lot of time around satellite systems, but what sets me apart is that I’ve also built up a wide range of tech skills outside the classroom. From engineering projects to hands-on tech work, I’ve had the chance to blend problem-solving, systems thinking, and people skills in a way that isn’t typical for most engineers.
  </p>
  <p>
  I like taking on challenges where I can learn something new, whether it’s in aerospace, engineering, or any technology-driven space. My goal is simple: keep growing, keep building, and apply my skills wherever they can make the biggest impact.
  </p>
  <br>
  <a href="mailto:rayalharaz@gmail.com">rayalharaz@gmail.com</a><br>
  <a href="https://www.linkedin.com/in/rayalhar" target="_blank">LinkedIn</a> ·
  <a href="https://github.com/rayalhar" target="_blank">GitHub</a><br><br>
  <a href="https://drive.google.com/uc?export=download&id=1d4pCs4y9w8Ogq-VaR6GiQuRELpzx6r0-" target="_blank"
     style="display:inline-block;padding:8px 12px;margin-top:6px;border:1px solid #007acc;
            border-radius:6px;background:#007acc;color:#fff;text-decoration:none;font-weight:bold;">
     ⬇ Download My Résumé
  </a>
