title: Ray Al Haraz
logo: /assets/img/headshot.jpg
theme: jekyll-theme-minimal

# This text renders in the LEFT sidebar under your name/photo.
description: |
  Aerospace Engineer — University at Buffalo (2025)<br>
  <a href="mailto:rayalharaz@gmail.com">rayalharaz@gmail.com</a><br>
  <a href="https://www.linkedin.com/in/rayalhar" target="_blank">LinkedIn</a> ·
  <a href="https://github.com/rayalhar" target="_blank">GitHub</a><br><br>
  <a href="https://drive.google.com/uc?export=download&id=1d4pCs4y9w8Ogq-VaR6GiQuRELpzx6r0-" target="_blank"
     style="display:inline-block;padding:8px 12px;margin-top:6px;border:1px solid #007acc;
            border-radius:6px;background:#007acc;color:#fff;text-decoration:none;font-weight:bold;">
     ⬇ Download My Résumé
  </a>
